server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb+srv://gonzalo:1234@atlascluster.r4rdhzc.mongodb.net/microservicios?retryWrites=true&w=majority

  application:
    name: CALIFICACION-SERVICE

  config:
    enabled: false
    import: optional:configserver:instead

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka